# Infranet.properties file.
# Contains configuration parameters for the PCM Java Server.

# java servers port #
infranet.server.portNr = 11940

# the log file that the java server will log msgs to
infranet.log.file=/home/applmgr/app/brm111/BRM/15.0.1/BRM15/BRM/var/eai_js/eai_js.pinlog

# the name of the application that the java server will
# use in it's log msgs 
infranet.log.name=PCMJavaServer

# log all msgs
infranet.log.level=1

# defines the Publish Handler 
infranet.opcode.handler.PUBLISH_GEN_PAYLOAD=com.portal.eai.PublishHandler

#defines config file for payload generator
infranet.eai.configFile=./payloadconfig.xml

########################################################
SSL configuration
########################################################
# To  enable SSL, make sure to provide correct values for below config entries. e.g wallet location and filename etc.
infranet.pcp.ssl.enabled = false
# To set the ciphersuites to be used.You can specify multiple ciphers seperated by commas.
#infranet.pcp.ssl.handshake.ciphersuites = TLS_RSA_WITH_AES_128_CBC_SHA

#TLS Versions - default value false is to support TLSv1.2. Keep this value as true to  support both TLSv1.3 ,TLSv1.2
#infranet.pcp.ssl.enable_tlsv13=true

# To enable SSL 2 way authentication
infranet.pcp.ssl.client_auth = false
# Oracle wallet location
infranet.pcp.ssl.wallet.location = /home/applmgr/app/brm111/BRM/15.0.1/BRM15/BRM/wallet/server
infranet.pcp.ssl.wallet.filename = cwallet.sso
