#
# primary database
#
0.0.0.1_user_name=pin
#0.0.0.1_user_password=<user password>
0.0.0.1_instance_name=amtdb1.portal.com
0.0.0.1_primary=true
# add below entries if using service name
#0.0.0.1_db_host=<host>
#0.0.0.1_db_port=<port>
#0.0.0.1_db_service_name=<svcname>

# AMT mover 
0.0.0.1_mover_log_file_dir=/u01/app/oracle/admin/amtdb1/udump
0.0.0.1_mover_log_file_flag=Y
0.0.0.1_grp_srch_log_file_dir=/u01/app/oracle/admin/amtdb1/udump
0.0.0.1_grp_srch_log_file_flag=Y
#
# secondary database 
#
0.0.0.2_user_name=pin
#0.0.0.2_user_password=<user password>
0.0.0.2_instance_name=amtdb2.portal.com
0.0.0.2_primary=false
# add below entries if using service name
#0.0.0.2_db_host=<host>
#0.0.0.2_db_port=<port>
#0.0.0.2_db_service_name=<svcname>
# AMT mover
0.0.0.2_mover_log_file_dir=/u01/app/oracle/admin/amtdb2/udump
0.0.0.2_mover_log_file_flag=Y
0.0.0.2_grp_srch_log_file_dir=/u01/app/oracle/admin/amtdb1/udump
0.0.0.2_grp_srch_log_file_flag=Y
#
# controller definitions
#
controller_1_log_directory=/home/hades/users/jkaemmer/tmp
controller_1_port_number=18566
controller_1_server=shark
controller_1_thread_count=2
controller_1_syslog_priority=7
controller_1_event_generation=false
controller_1_concurrent_job_number=20
controller_1_hold_period=120
controller_1_amt_queue_owner_name=pinq
controller_1_amt_queue_name=ifw_sync_queue_amt

#
# pin_amt definitions
# 
pin_amt_log_directory=/home/hades/users/jkaemmer/tmp

#========================================================================
# publish_migrated_objects
#
# comma-separated list of storable classes in the format :
# publish_migrated_objects=/billinfo,/service,/purchased_product
#
# If the entry is commented, the feature is disabled
# default = (disable)
#========================================================================
#publish_migrated_objects=/billinfo,/service

#
# CM connection properties
#   connect string in the format
#   infranet.connection=pcp://LOGIN:PASSWORD@HOSTNAME:PORT/service/pcm_client
#infranet.connection=pcp://root.0.0.0.1:&aes|08|0D5E11BFDD97D2769D9B0DBFBD1BBF7E5D40C305EDF3D77DF111AAB8F781E92122@hostname:12009/service/pcm_client
infranet.login.type=1
timos_migration=false

timesten_enabled=false
target_pin_home=/opt/portal/7.5

timesten_node_1_user=pin
timesten_node_1_pwd=<password>
timesten_node_1_dsn=tt_0.0.0.1
timesten_node_1_db_id=0.0.0.1
