@echo. 
@echo This command file executes DOC1/EMFE for the sample job for Adobe PDF output
@echo DOC1EMFE will run with the initialization file /home/applmgr/app/brm111/BRM/15.0.1/BRM15/BRM/sys/data/config/DOC1HOST/RESOURCE/PORTALPD.INI
@echo Output will be generated in /home/applmgr/app/brm111/BRM/15.0.1/BRM15/BRM/sys/data/config/DOC1HOST/tmp
@echo. 
doc1emfe ini=/home/applmgr/app/brm111/BRM/15.0.1/BRM15/BRM/sys/data/config/DOC1HOST/RESOURCE/PORTALPD.INI
