*Client Information
CLNTNM United Parcel Service
CLNTNMBR U1215
CLNTPHN 1-800-353-9877
CLNTADDR1 100 Main Street
CLNTADDR2 Anytown, IL 60069
*Benefits Center Information
BCNM UPS Benefits Service Center
BCRPRS UPS Benefits Service Center Representatives
BCPHN 1-800-353-9877
BCADDR1 100 Half Day Road
BCADDR2 Lincolnshire, IL 60069-9971
BCFROMTM 8 a.m.
BCTOTM 8 p.m.
IVRFROMTM 6 a.m.
IVRTOTM 2 a.m.,
IVR Interactive Voice Response System
COBRAADMINNM COBRA Administrator
COBRAADMINPHN 1-555-123-4567
ERISAADMINNM ERISA Administrator
*Statement Information
400 Version-Rehire within the Same Plan Year
401 Version-Coverage Change
402 Version-On Demand
403 Version-Leave of Absence
403A Coverage Termination Notice
*HGBPLANNM Welfare Plan  *** UPS has different names based on ee status
HGBPLANNMACT UPS Flexible Benefits Plan         
HGBPLANNMACTUN 
HGBPLANNMACTUX UPS Health and Welfare Package
HGBPLANNMCOBA UPS Flexible Benefits Plan  
HGBPLANNMCOBAUN 
HGBPLANNMCOBAUX UPS Health and Welfare Package
HGBPLANNMCOBR UPS Retired Employees' Health Care Plan
HGBPLANNMCOBRUN 
HGBPLANNMCOBRUX UPS Health and Welfare Package for Retired Employees
HGBPLANNMINDUN  
HGBPLANNMINLG   
HGBPLANNMINLGUF UPS Flexible Benefits Plan
HGBPLANNMINLGUN 
HGBPLANNMINLGUX UPS Health and Welfare Package
HGBPLANNMLOA UPS Flexible Benefits Plan   
HGBPLANNMLOAUN  
HGBPLANNMLOAUX UPS Health and Welfare Package
HGBPLANNMLTD UPS Flexible Benefits Plan
HGBPLANNMLTDUN  
HGBPLANNMLTDUX UPS Health and Welfare Package
HGBPLANNMRET UPS Retired Employees' Health Care Plan
HGBPLANNMRETUN  
HGBPLANNMRETUX UPS Health and Welfare Package for Retired Employees
HGBPLANNMSRVA UPS Flexible Benefits Plan  
HGBPLANNMSRVAUN 
HGBPLANNMSRVAUX UPS Health and Welfare Package
HGBPLANNMSRVR UPS Retired Employees' Health Care Plan
HGBPLANNMSRVRUN 
HGBPLANNMSRVRUX UPS Health and Welfare Package for Retired Employees
HGBPLANNMTERM UPS Flexible Benefits Plan
HGBPLANNMTERMUN 
HGBPLANNMTERMUX UPS Health and Welfare Package
* 
TXPYSDSC Soc. Sec. Num.
TXPYLDSC Social Security Number
SGNTDESC Signature
DTDESC Date
OPTDESC Option
COVDESC Coverage
CATDESC Category
COVCATDESC Coverage Category
TAXDESC Tax
RSPNPLANNM Smoker
FSADESC Reimbursement Accounts
COBRADESC COBRA
BEGINDESC Begin
ENDDESC End
*Personal Information Section
LINE1DESC Statement Date
LINE2DESC Soc. Sec. Num.
LINE3DESC 
LINE4DESC 
*Family Information Section
IVRVAL1 (1 = Yes 2 = No)
IVRVAL2 (1 = Spouse 2 = Child 3 = Stepchild)
IVRVAL3 (1 = Male 2 = Female)
IVRVAL4  
PERLBL1 Social Security Number
PERLBL2 Name
PERLBL3 Relationship
PERLBL4 Birth Date
PERLBL5 Gender
PERLBL6 Medicare Eligible
PERLBL7 Full-Time Student Age 19-25
PERLBL8 Qualified Beneficiary
PERLBL9 Incapacitated Dependent
COVLBL1 Medical Plan 
COVLBL2 Medicare Eligibility
COVLBL3 Dental Plan 
COVLBL4 Vision Plan
COVLBL5 Vision Plan
PROLBL1 Medical Provider ID*
PROLBL2 Current Patient
PROLBL3 Second Medical Provider
PROLBL4 Current Patient
PROLBL5 Third Medical Provider
PROLBL6 Current Patient
PROLBL7 Dental Provider ID*
PROLBL8 Current Patient
Y Yes
N No
*Statement Names
H001B0COEANN Confirmation of Enrollment
H001B0COENH Confirmation of Enrollment
H001B0COECC Confirmation of Enrollment  
H001B0COECE Confirmation of Enrollment
H001B0COEOD Confirmation of Enrollment
H001B0LOC Confirmation of Coverage
H001B0LOCN Confirmation of Coverage
H001B0COMLOA Confirmation of Coverage
H001B0RETLOA Confirmation of Coverage
H001B0SEV Confirmation of Coverage
H001B0RET Confirmation of Coverage
H001B0RETW Confirmation of Coverage 
H001B0SS Confirmation of Coverage
H001B0REHIRE Confirmation of Coverage
H001B0COVCAN Confirmation of Coverage
H001B0RTCG Confirmation of Coverage
H001B0LTD Confirmation of Coverage
H001B0SDC Confirmation of Coverage
H001B0DLC Confirmation of Coverage
H001B0DTN Coverage Termination Notice
H002B0 Beneficiary Designation
H003B0 Beneficiary Confirmation Notice
H004B0 Dependent Eligibility Notice
H004B0FT Full-Time Student Verification Form
H005B0 Certificate of Group Health Plan Coverage
H006B0 Evidence of Insurability Form
H007B0 COBRA Rights Notice
H008B0 COBRA Enrollment Notice
H009B0 COBRA Annual Enrollment Notice
H010B0 COBRA Coverage Termination Notice
H010B0A Coverage Termination Notice
H011B0 COBRA Confirmation of Enrollment
H012B0 Conversion Notice
H013B0ID Incapacitated Dependent Cover Letter
H013B0AA Absolute Assignment Cover Letter
H013B0EOI Evidence of Insurability           Cover Letter
H013B0411 Proof of Pension Request               
H014B0 Enrollment Worksheet
M001B0 PIN Notice
M002B0 Confirmation of PIN Reset
M003B0 Confirmation of Temporary Address
*EWS Information
MATRIX05COVCAT1DESC $.30 per $1,000 of coverage
MATRIX05COVCAT2DESC $.35 per $1,000 of coverage
MATRIX06COVCAT1DESC $.30 per $1,000 of coverage
MATRIX06COVCAT2DESC $.35 per $1,000 of coverage
MATRIX11COVCAT1DESC $.35 per $1,000 of coverage
MATRIX12COVCAT1DESC $.35 per $1,000 of coverage
*Dependent Loss of Coverage-COE codes
XX Reached age 25 and ineligible for coverage
YY Reached age 19 and not full-time student or incpacitated
ZZ Has not been recertified
*Code Translations
CC 19
S Single
M Married
SP Spouse
CH Child
OT Other
*States and Provinces
AB Alberta
AK Alaska
AL Alabama
AR Arkansas
AZ Arizona
BC British Columbia
CA California
CO Colorado
CT Connecticut
DC District of Columbia
DE Delaware
FL Florida
GA Georgia
GU Guam
HI Hawaii
IA Iowa
ID Idaho
IL Illinois
IN Indiana
KS Kansas
KY Kentucky
LA Louisiana
MA Massachusetts
MB Manitoba
MD Maryland
ME Maine
MI Michigan
MN Minnesota
MO Missouri
MS Mississippi
MT Montana
NB New Brunswick
NC North Carolina
ND North Dakota
NE Nebraska
NF Newfoundland
NH New Hampshire
NJ New Jersey
NM New Mexico
NS Nova Scotia
NT Northwest Territory
NV Nevada
NY New York
OH Ohio
OK Oklahoma
ON Ontario
OR Oregon
PA Pennsylvania
PE Prince Edward Island
PR Puerto Rico
QC Province of Quebec
RI Rhode Island
SC South Carolina
SD South Dakota
SK Saskatchewan
TN Tennessee
TX Texas
UT Utah
VA Virginia
VI Virgin Islands
VT Vermont
WA Washington
WI Wisconsin
WV West Virginia
WY Wyoming
YT Yukon Territory
*Months
01 January
02 February
03 March
04 April
05 May
06 June
07 July
08 August
09 September
10 October
11 November
12 December
*EOI form Control Numbers
CNACTUXY 702774
CNACTUXN 702775
CNACTY 697883
CNACTN 697884
