/*
 *      @(#) % %
 *    
* Copyright (c) 1996, 2018, Oracle and/or its affiliates. All rights reserved.
 *    
 *      This material is the confidential property of Oracle Corporation or its
 *      licensors and may be used, reproduced, stored or transmitted only in
 *      accordance with a valid Oracle license or sublicense agreement.
 */

#ifndef __DPARSE_INTERNAL_H
#define __DPARSE_INTERNAL_H

/*******************************************************************
 * Enum of all tokens
 *******************************************************************/

typedef enum pin_dparse_tok {
	PIN_DPARSE_TOK_NULL		= 0,
	PIN_DPARSE_TOK_POID		= 1,
	PIN_DPARSE_TOK_STR		= 2,
	PIN_DPARSE_TOK_ARRAY		= 3,
	PIN_DPARSE_TOK_SUBSTRUCT	= 4,
	PIN_DPARSE_TOK_NUM		= 5,
	PIN_DPARSE_TOK_INT		= 6,
	PIN_DPARSE_TOK_UINT		= 7,
	PIN_DPARSE_TOK_ENUM		= 8,
	PIN_DPARSE_TOK_TSTAMP		= 9,
	PIN_DPARSE_TOK_BUF		= 10,
	PIN_DPARSE_TOK_BINSTR		= 11,
	PIN_DPARSE_TOK_EBUF		= 12,
	PIN_DPARSE_TOK_LABEL		= 13,
	PIN_DPARSE_TOK_DESCR		= 14,
	PIN_DPARSE_TOK_ID		= 15,
	PIN_DPARSE_TOK_LENGTH		= 16,
	PIN_DPARSE_TOK_ORDER		= 17,
	PIN_DPARSE_TOK_CREATE		= 18,
	PIN_DPARSE_TOK_MODIFY		= 19,
	PIN_DPARSE_TOK_STORABLE		= 20,
	PIN_DPARSE_TOK_CLASS		= 21,
	PIN_DPARSE_TOK_OPEN_CURLY	= 22,
	PIN_DPARSE_TOK_CLOSE_CURLY	= 23,
	PIN_DPARSE_TOK_EQUALS		= 24,
	PIN_DPARSE_TOK_SEMICOLON	= 25,
	PIN_DPARSE_TOK_NAME		= 26,
	PIN_DPARSE_TOK_EOF		= 27,
	PIN_DPARSE_TOK_ERR		= 28,
	PIN_DPARSE_TOK_QUOTED_STR	= 29,
	PIN_DPARSE_TOK_REQUIRED		= 30,
	PIN_DPARSE_TOK_OPTIONAL		= 31,
	PIN_DPARSE_TOK_PROHIBITED	= 32,
	PIN_DPARSE_TOK_SYSTEM		= 33,
	PIN_DPARSE_TOK_WRITEABLE	= 34,
	PIN_DPARSE_TOK_NONWRITEABLE	= 35,
	PIN_DPARSE_TOK_QUOTE_STR	= 36,
	PIN_DPARSE_TOK_IMPL		= 37,
	PIN_DPARSE_TOK_SQL_COLUMN	= 38,
	PIN_DPARSE_TOK_SQL_TABLE	= 39,
	PIN_DPARSE_TOK_SQL_STORAGE	= 40,
	PIN_DPARSE_TOK_OBJ		= 41,
	PIN_DPARSE_TOK_LOCATION		= 42,
	PIN_DPARSE_TOK_ATTRVAL		= 43,
	PIN_DPARSE_TOK_ATTRIBUTE	= 44,
	PIN_DPARSE_TOK_MULTIVALUED	= 45,
	PIN_DPARSE_TOK_RDN_PIECE	= 46,
	PIN_DPARSE_TOK_ENTRY_TYPE	= 47,
	PIN_DPARSE_TOK_SQL_COLUMN_PREFIX= 48,
	PIN_DPARSE_TOK_SEQ_START	= 49,
	PIN_DPARSE_TOK_DECIMAL		= 50,	
	PIN_DPARSE_TOK_READ_ACCESS	= 51,
	PIN_DPARSE_TOK_WRITE_ACCESS	= 52,
	PIN_DPARSE_TOK_SELF		= 53,
	PIN_DPARSE_TOK_BRAND_LINEAGE	= 54,
	PIN_DPARSE_TOK_BRAND		= 55,
	PIN_DPARSE_TOK_ANCESTRAL_LINEAGE= 56,
	PIN_DPARSE_TOK_GLOBAL		= 57,
	PIN_DPARSE_TOK_AUDITABLE	= 58,
	PIN_DPARSE_TOK_ENCRYPTABLE	= 59,
	/* "WRITEABLE" is incorrect spelling, so created a new token to accept
	 * the correct spelling and co-exist with the incorrect spelling.
	 */
	PIN_DPARSE_TOK_WRITABLE		= 60,
	PIN_DPARSE_TOK_NONWRITABLE	= 61,
	PIN_DPARSE_TOK_CREATE_ACCESS	= 62,
	PIN_DPARSE_TOK_BRAND_OWNER	= 63,
	PIN_DPARSE_TOK_ROOT		= 64,
	PIN_DPARSE_TOK_ANY		= 65,
	PIN_DPARSE_TOK_LINK_OBJECT	= 66,
	PIN_DPARSE_TOK_LINK_ATTRIBUTE	= 67,
	PIN_DPARSE_TOK_OBJECTCLASS	= 68,
	PIN_DPARSE_TOK_IS_PARTITIONED   = 69,
	PIN_DPARSE_TOK_PARTITION_MODE   = 70,
	PIN_DPARSE_TOK_FINITE           = 71,
	PIN_DPARSE_TOK_HISTORIC         = 72,
	PIN_DPARSE_TOK_RESIDENCY_TYPE   = 73,
	PIN_DPARSE_TOK_SERIALIZABLE   	= 74,
	PIN_DPARSE_TOK_AUDIT_SCHEME     = 75,
	PIN_DPARSE_TOK_AUDIT_SCHEME_COMPACTED = 76,
	PIN_DPARSE_TOK_AUDIT_SCHEME_EXPANDED = 77,
	PIN_DPARSE_TOK_QUERYABLE_ON_AUDIT  = 78,
	PIN_DPARSE_TOK_IGNORE_ON_AUDIT  = 79,
	PIN_DPARSE_TOK_YES  = 80,
	PIN_DPARSE_TOK_NO  = 81,
	PIN_DPARSE_TOK_VIRTUAL_FLAG   = 82,
	PIN_DPARSE_TOK_EVENT_TYPE   = 83,
	PIN_DPARSE_TOK_INT64		= 84,
} pin_dparse_tok_t;



/*******************************************************************
 * Defines of all of the match text strings which will be translated
 * into enum tokens.
 *******************************************************************/

#define PIN_DPARSE_STOK_POID		"POID"
#define PIN_DPARSE_STOK_STR			"STRING"
#define PIN_DPARSE_STOK_ARRAY		"ARRAY"
#define PIN_DPARSE_STOK_SUBSTRUCT	"SUBSTRUCT"
#define PIN_DPARSE_STOK_NUM			"NUM"
#define PIN_DPARSE_STOK_INT			"INT"
#define PIN_DPARSE_STOK_UINT		"UINT"
#define PIN_DPARSE_STOK_ENUM		"ENUM"
#define PIN_DPARSE_STOK_TSTAMP		"TIMESTAMP"
#define PIN_DPARSE_STOK_BUF			"BUF"
#define PIN_DPARSE_STOK_BINSTR		"BINSTR"
#define PIN_DPARSE_STOK_EBUF		"EBUF"
#define PIN_DPARSE_STOK_OBJ			"OBJ"
#define PIN_DPARSE_STOK_LABEL		"LABEL"
#define PIN_DPARSE_STOK_DESCR		"DESCR"
#define PIN_DPARSE_STOK_ID			"ID"
#define PIN_DPARSE_STOK_LENGTH		"LENGTH"
#define PIN_DPARSE_STOK_ORDER		"ORDER"
#define PIN_DPARSE_STOK_CREATE		"CREATE"
#define PIN_DPARSE_STOK_REQUIRED	"REQUIRED"
#define PIN_DPARSE_STOK_OPTIONAL	"OPTIONAL"
#define PIN_DPARSE_STOK_PROHIBITED	"PROHIBITED"
#define PIN_DPARSE_STOK_SYSTEM		"SYSTEM"
#define PIN_DPARSE_STOK_WRITEABLE	"WRITEABLE"
#define PIN_DPARSE_STOK_NONWRITEABLE	"NOT_WRITEABLE"
/* "WRITEABLE" is incorrect spelling, so created a new token to accept
 * the correct spelling and co-exist with the incorrect spelling.
 */
#define PIN_DPARSE_STOK_WRITABLE	"WRITABLE"
#define PIN_DPARSE_STOK_NONWRITABLE	"NOT_WRITABLE"
#define PIN_DPARSE_STOK_MODIFY		"MODIFY"
#define PIN_DPARSE_STOK_STORABLE	"STORABLE"
#define PIN_DPARSE_STOK_CLASS		"CLASS"
#define PIN_DPARSE_STOK_OPEN_CURLY	"{"
#define PIN_DPARSE_STOK_CLOSE_CURLY	"}"
#define PIN_DPARSE_STOK_EQUALS		"="
#define PIN_DPARSE_STOK_SEMICOLON	";"
#define PIN_DPARSE_STOK_IMPL		"IMPLEMENTATION"
#define PIN_DPARSE_STOK_SQL_COLUMN	"SQL_COLUMN"
#define PIN_DPARSE_STOK_SQL_COLUMN_PREFIX	"SQL_COLUMN_PREFIX"
#define PIN_DPARSE_STOK_SQL_TABLE	"SQL_TABLE"
#define PIN_DPARSE_STOK_SQL_STORAGE	"SQL_STORAGE"
#define PIN_DPARSE_STOK_ORACLE7		"ORACLE7"
#define PIN_DPARSE_STOK_SQLGENERIC	"SQLGENERIC"
#define PIN_DPARSE_STOK_SQLSERVER7	"SQLSERVER7"
#define PIN_DPARSE_STOK_LDAPV3		"LDAPV3"
#define	PIN_DPARSE_STOK_LOCATION	"LOCATION"
#define	PIN_DPARSE_STOK_ATTRVAL		"ATTRVAL"
#define	PIN_DPARSE_STOK_ATTRIBUTE	"ATTRIBUTE"
#define	PIN_DPARSE_STOK_MULTIVALUED	"MULTIVALUED"
#define	PIN_DPARSE_STOK_RDN_PIECE	"RDN_PIECE"
#define PIN_DPARSE_STOK_UNUSED		"UNUSED"
#define	PIN_DPARSE_STOK_ENTRY_TYPE	"ENTRY_TYPE"
#define	PIN_DPARSE_STOK_SEQ_START	"SEQ_START"
#define	PIN_DPARSE_STOK_DECIMAL		"DECIMAL"
#define PIN_DPARSE_STOK_READ_ACCESS	"READ_ACCESS"
#define PIN_DPARSE_STOK_WRITE_ACCESS	"WRITE_ACCESS"
#define PIN_DPARSE_STOK_CREATE_ACCESS	"CREATE_ACCESS"
#define PIN_DPARSE_STOK_SELF		"SELF"
#define PIN_DPARSE_STOK_BRAND_LINEAGE	"BRANDLINEAGE"
#define PIN_DPARSE_STOK_BRAND		"BRAND"
#define PIN_DPARSE_STOK_ANCESTRAL_LINEAGE "ANCESTRALLINEAGE"
#define PIN_DPARSE_STOK_GLOBAL		"GLOBAL"
#define	PIN_DPARSE_STOK_AUDITABLE	"AUDITABLE"
#define	PIN_DPARSE_STOK_ENCRYPTABLE	"ENCRYPTABLE"
#define PIN_DPARSE_STOK_BRAND_OWNER	"BRANDOWNER"
#define PIN_DPARSE_STOK_ROOT		"ROOT"
#define PIN_DPARSE_STOK_ANY		"ANY"
#define	PIN_DPARSE_STOK_LINK_OBJECT	"LINK_OBJECT"
#define	PIN_DPARSE_STOK_LINK_ATTRIBUTE	"LINK_ATTRIBUTE"
#define	PIN_DPARSE_STOK_OBJECTCLASS	"OBJECTCLASS"
#define PIN_DPARSE_STOK_IS_PARTITIONED  "IS_PARTITIONED"
#define PIN_DPARSE_STOK_PARTITION_MODE  "PARTITION_MODE"
#define PIN_DPARSE_STOK_FINITE          "FINITE"
#define PIN_DPARSE_STOK_HISTORIC        "HISTORIC"
#define PIN_DPARSE_STOK_RESIDENCY_TYPE  "RESIDENCY_TYPE"
#define	PIN_DPARSE_STOK_SERIALIZABLE	"SERIALIZABLE"
#define	PIN_DPARSE_STOK_AUDIT_SCHEME	"AUDIT_SCHEME"
#define	PIN_DPARSE_STOK_AUDIT_SCHEME_COMPACTED	"COMPACTED"
#define	PIN_DPARSE_STOK_AUDIT_SCHEME_EXPANDED	"EXPANDED"
#define	PIN_DPARSE_STOK_QUERYABLE_ON_AUDIT	"QUERYABLE_ON_AUDIT"
#define	PIN_DPARSE_STOK_IGNORE_ON_AUDIT	"IGNORE_ON_AUDIT"
#define PIN_DPARSE_STOK_YES 		"YES"
#define PIN_DPARSE_STOK_NO 		"NO"
#define PIN_DPARSE_STOK_VIRTUAL_FLAG    "VIRTUAL_FLAG"
#define PIN_DPARSE_STOK_EVENT_TYPE  	"EVENT_TYPE"
#define PIN_DPARSE_STOK_INT64  	"INT64"

/***********************************************************************
 * These are char versions of a couple of the STOK's listed above that
 * are needed in a few place, namely as token terminators
 ***********************************************************************/

#define PIN_DPARSE_CTOK_OPEN_CURLY	'{'
#define PIN_DPARSE_CTOK_CLOSE_CURLY	'}'
#define PIN_DPARSE_CTOK_EQUALS		'='
#define PIN_DPARSE_CTOK_SEMICOLON	';'



/*******************************************************************
 * Struct to be used in match table
 *******************************************************************/

typedef struct pin_dparse_tok_match {
	pin_dparse_tok_t	token;
	char				*string;
} pin_dparse_tok_match_t;

/***********************************************************************
 * Table which matches up many of the token enums with their equivelent
 * text strings
 ***********************************************************************/

static pin_dparse_tok_match_t token_table[] = {
	{ PIN_DPARSE_TOK_POID,		(char *)PIN_DPARSE_STOK_POID	},
	{ PIN_DPARSE_TOK_STR,		(char *)PIN_DPARSE_STOK_STR	},
	{ PIN_DPARSE_TOK_ARRAY,		(char *)PIN_DPARSE_STOK_ARRAY	},
	{ PIN_DPARSE_TOK_SUBSTRUCT,	(char *)PIN_DPARSE_STOK_SUBSTRUCT},
	{ PIN_DPARSE_TOK_NUM,		(char *)PIN_DPARSE_STOK_NUM	},
	{ PIN_DPARSE_TOK_INT,		(char *)PIN_DPARSE_STOK_INT	},
	{ PIN_DPARSE_TOK_UINT,		(char *)PIN_DPARSE_STOK_UINT	},
	{ PIN_DPARSE_TOK_ENUM,		(char *)PIN_DPARSE_STOK_ENUM	},
	{ PIN_DPARSE_TOK_TSTAMP,	(char *)PIN_DPARSE_STOK_TSTAMP	},
	{ PIN_DPARSE_TOK_BUF,		(char *)PIN_DPARSE_STOK_BUF	},
	{ PIN_DPARSE_TOK_BINSTR,	(char *)PIN_DPARSE_STOK_BINSTR	},
	{ PIN_DPARSE_TOK_EBUF,		(char *)PIN_DPARSE_STOK_EBUF	},
	{ PIN_DPARSE_TOK_OBJ,		(char *)PIN_DPARSE_STOK_OBJ	},
	{ PIN_DPARSE_TOK_LABEL,		(char *)PIN_DPARSE_STOK_LABEL	},
	{ PIN_DPARSE_TOK_DESCR,		(char *)PIN_DPARSE_STOK_DESCR	},
	{ PIN_DPARSE_TOK_ID,		(char *)PIN_DPARSE_STOK_ID	},
	{ PIN_DPARSE_TOK_LENGTH,	(char *)PIN_DPARSE_STOK_LENGTH	},
	{ PIN_DPARSE_TOK_ORDER,		(char *)PIN_DPARSE_STOK_ORDER	},
	{ PIN_DPARSE_TOK_CREATE,	(char *)PIN_DPARSE_STOK_CREATE	},
	{ PIN_DPARSE_TOK_REQUIRED,	(char *)PIN_DPARSE_STOK_REQUIRED},
	{ PIN_DPARSE_TOK_OPTIONAL,	(char *)PIN_DPARSE_STOK_OPTIONAL},
	{ PIN_DPARSE_TOK_PROHIBITED,(char *)PIN_DPARSE_STOK_PROHIBITED	},
	{ PIN_DPARSE_TOK_SYSTEM,	(char *)PIN_DPARSE_STOK_SYSTEM	},
	{ PIN_DPARSE_TOK_MODIFY,	(char *)PIN_DPARSE_STOK_MODIFY	},
	{ PIN_DPARSE_TOK_WRITEABLE,	(char *)PIN_DPARSE_STOK_WRITEABLE},
	{ PIN_DPARSE_TOK_NONWRITEABLE,(char *)PIN_DPARSE_STOK_NONWRITEABLE},
	/* "WRITEABLE" is incorrect spelling, so created a new token to accept
	 * the correct spelling and co-exist with the incorrect spelling.
	 */
	{ PIN_DPARSE_TOK_WRITABLE,	(char *)PIN_DPARSE_STOK_WRITABLE},
	{ PIN_DPARSE_TOK_NONWRITABLE,(char *)PIN_DPARSE_STOK_NONWRITABLE},
	{ PIN_DPARSE_TOK_STORABLE,	(char *)PIN_DPARSE_STOK_STORABLE},
	{ PIN_DPARSE_TOK_CLASS,		(char *)PIN_DPARSE_STOK_CLASS	},
	{ PIN_DPARSE_TOK_OPEN_CURLY,(char *)PIN_DPARSE_STOK_OPEN_CURLY	},
	{ PIN_DPARSE_TOK_CLOSE_CURLY,(char *)PIN_DPARSE_STOK_CLOSE_CURLY},
	{ PIN_DPARSE_TOK_EQUALS,	(char *)PIN_DPARSE_STOK_EQUALS	},
	{ PIN_DPARSE_TOK_SEMICOLON,	(char *)PIN_DPARSE_STOK_SEMICOLON},
	{ PIN_DPARSE_TOK_IMPL,		(char *)PIN_DPARSE_STOK_IMPL	},
	{ PIN_DPARSE_TOK_SQL_COLUMN,(char *)PIN_DPARSE_STOK_SQL_COLUMN	},
	{ PIN_DPARSE_TOK_SQL_TABLE,	(char *)PIN_DPARSE_STOK_SQL_TABLE},
	{ PIN_DPARSE_TOK_SQL_STORAGE,(char *)PIN_DPARSE_STOK_SQL_STORAGE},

	{ PIN_DPARSE_TOK_LOCATION, 	(char *)PIN_DPARSE_STOK_LOCATION},
	{ PIN_DPARSE_TOK_ATTRVAL, 	(char *)PIN_DPARSE_STOK_ATTRVAL},
	{ PIN_DPARSE_TOK_ATTRIBUTE, 	(char *)PIN_DPARSE_STOK_ATTRIBUTE},
	{ PIN_DPARSE_TOK_MULTIVALUED, 	(char *)PIN_DPARSE_STOK_MULTIVALUED},
	{ PIN_DPARSE_TOK_RDN_PIECE, 	(char *)PIN_DPARSE_STOK_RDN_PIECE},
	{ PIN_DPARSE_TOK_ENTRY_TYPE, 	(char *)PIN_DPARSE_STOK_ENTRY_TYPE},
	{ PIN_DPARSE_TOK_SQL_COLUMN_PREFIX,
			(char *)PIN_DPARSE_STOK_SQL_COLUMN_PREFIX	},
	{ PIN_DPARSE_TOK_SEQ_START, 	(char *)PIN_DPARSE_STOK_SEQ_START},
	{ PIN_DPARSE_TOK_DECIMAL, 	(char *)PIN_DPARSE_STOK_DECIMAL},
	{ PIN_DPARSE_TOK_READ_ACCESS,	(char *)PIN_DPARSE_STOK_READ_ACCESS},
	{ PIN_DPARSE_TOK_WRITE_ACCESS,	(char *)PIN_DPARSE_STOK_WRITE_ACCESS},
	{ PIN_DPARSE_TOK_CREATE_ACCESS,	(char *)PIN_DPARSE_STOK_CREATE_ACCESS},
	{ PIN_DPARSE_TOK_SELF,		(char *)PIN_DPARSE_STOK_SELF},
	{ PIN_DPARSE_TOK_BRAND_LINEAGE,	(char *)PIN_DPARSE_STOK_BRAND_LINEAGE},
	{ PIN_DPARSE_TOK_BRAND,		(char *)PIN_DPARSE_STOK_BRAND},
	{ PIN_DPARSE_TOK_ANCESTRAL_LINEAGE,	
			(char *)PIN_DPARSE_STOK_ANCESTRAL_LINEAGE},
	{ PIN_DPARSE_TOK_GLOBAL,	(char *)PIN_DPARSE_STOK_GLOBAL},
	{ PIN_DPARSE_TOK_AUDITABLE,	(char *)PIN_DPARSE_STOK_AUDITABLE},
	{ PIN_DPARSE_TOK_ENCRYPTABLE,	(char *)PIN_DPARSE_STOK_ENCRYPTABLE},
	{ PIN_DPARSE_TOK_ROOT,		(char *)PIN_DPARSE_STOK_ROOT},
	{ PIN_DPARSE_TOK_BRAND_OWNER,	(char *)PIN_DPARSE_STOK_BRAND_OWNER },
	{ PIN_DPARSE_TOK_ANY,		(char *)PIN_DPARSE_STOK_ANY},
	{ PIN_DPARSE_TOK_LINK_OBJECT, 	(char *)PIN_DPARSE_STOK_LINK_OBJECT},
	{ PIN_DPARSE_TOK_LINK_ATTRIBUTE, (char *)PIN_DPARSE_STOK_LINK_ATTRIBUTE},
	{ PIN_DPARSE_TOK_OBJECTCLASS, 	(char *)PIN_DPARSE_STOK_OBJECTCLASS},
	{PIN_DPARSE_TOK_IS_PARTITIONED, (char *)PIN_DPARSE_STOK_IS_PARTITIONED},
	{PIN_DPARSE_TOK_PARTITION_MODE, (char *)PIN_DPARSE_STOK_PARTITION_MODE},
	{PIN_DPARSE_TOK_FINITE, 	(char *)PIN_DPARSE_STOK_FINITE},
	{PIN_DPARSE_TOK_HISTORIC,	(char *)PIN_DPARSE_STOK_HISTORIC},	
	{PIN_DPARSE_TOK_RESIDENCY_TYPE, (char *)PIN_DPARSE_STOK_RESIDENCY_TYPE},
	{PIN_DPARSE_TOK_SERIALIZABLE, 	(char *)PIN_DPARSE_STOK_SERIALIZABLE},
	{PIN_DPARSE_TOK_AUDIT_SCHEME, 	(char *)PIN_DPARSE_STOK_AUDIT_SCHEME},
	{PIN_DPARSE_TOK_AUDIT_SCHEME_COMPACTED, (char *)PIN_DPARSE_STOK_AUDIT_SCHEME_COMPACTED},
	{PIN_DPARSE_TOK_AUDIT_SCHEME_EXPANDED, (char *)PIN_DPARSE_STOK_AUDIT_SCHEME_EXPANDED},
	{PIN_DPARSE_TOK_QUERYABLE_ON_AUDIT, (char *)PIN_DPARSE_STOK_QUERYABLE_ON_AUDIT},
	{PIN_DPARSE_TOK_IGNORE_ON_AUDIT, (char *)PIN_DPARSE_STOK_IGNORE_ON_AUDIT},
	{PIN_DPARSE_TOK_YES, (char *)PIN_DPARSE_STOK_YES},
	{PIN_DPARSE_TOK_NO, (char *)PIN_DPARSE_STOK_NO},
	{PIN_DPARSE_TOK_VIRTUAL_FLAG, (char *)PIN_DPARSE_STOK_VIRTUAL_FLAG},
	{ PIN_DPARSE_TOK_EVENT_TYPE, (char *)PIN_DPARSE_STOK_EVENT_TYPE},
	{ PIN_DPARSE_TOK_INT64, (char *)PIN_DPARSE_STOK_INT64},
	/* This is last one */
	{ PIN_DPARSE_TOK_NULL,		(char *)NULL		}

};


#endif 
