/*
 *	@(#)%Portal Version: pin_os_random.h:PlatformR2Int:1:2006-Sep-12 03:31:54 %
 *       
 *      Copyright (c) 1996 - 2006 Oracle. All rights reserved.
 *      	 
 *      This material is the confidential property of Oracle Corporation or its
 *      licensors and may be used, reproduced, stored or transmitted only in
 *      accordance with a valid Oracle license or sublicense agreement.
 */

#ifndef _pin_os_random_h_
#define _pin_os_random_h_

#ifndef _pin_os_types_h_
#include <pin_os_types.h>
#endif

#if defined(__cplusplus)
extern "C" {
#endif

/** Generate a random integral number
  *
  * This function returns a random integral number. In order to be thread
  * safe, this function requires you to provide the seed value, instead of
  * calling a separate seed function. You must set the seed value initially
  * and then pass in the pointer to this seed on each successive call to this
  * function. The seed value will be updated on each call, so basically you
  * are providing the function with a thread safe scratch pad.
  *
  * @param  seed    The ongoing seed value. See the function description for
  *                 details.
  *
  * @return The next available number in the random sequence.
  */
int32 pin_random(int32* const seed);


/** Generate a random floating point number
  *
  * The number returned by this function will be uniformily distributed over
  * the range 0.0 to 1.0. In order to be thread safe, this function requires
  * you to provide the seed value, instead of calling a separate seed function.
  * You must set the seed value initially and then pass in the pointer to this
  * seed on each successive call to this function. The seed value will be
  * updated on each call, so basically you are providing the function with a
  * thread safe scratch pad.
  *
  * @param  p_seed  The seed value. You must initialize it once, then pass it
  *                 back in on each subsequent call to pin_random(). Basically
  *                 you are providing it a scratch pad area, so that it can be
  *                 thread safe.
  *
  * @return The next available number in the random sequence.
  */
double pin_drand48(u_int64* const p_seed);


/** Generate a random floating point number
  *
  * The number returned by this function will be uniformily distributed over
  * the range 0.0 to 1.0. In order to be thread safe, this function requires
  * you to provide the seed value, instead of calling a separate seed function.
  * You must set the seed value initially and then pass in the pointer to this
  * seed on each successive call to this function. The seed value will be
  * updated on each call, so basically you are providing the function with a
  * thread safe scratch pad.
  *
  * @param  p_seed  The seed value. You must initialize it once, then pass it
  *                 back in on each subsequent call to pin_random(). Basically
  *                 you are providing it a scratch pad area, so that it can be
  *                 thread safe.
  *
  * @return The next available number in the random sequence.
  */
u_int32 pin_lrand48(u_int64* const p_seed);



/** Generate a buffer with specified number of random bytes
  *
  * The char pointer returned by this function will point to a buffer that
  * has the specified number of random bytes, these random bytes will be 
  * read from the device file /dev/urandom.
  *
  * @param  buf_len Integer value specifying the number of random bytes to 
  *                 be generated by reading form /dev/urandom device file.
  *
  * @param rebufp   error buffer, this will be set in case there is any 
  *                 issue in reading the random bytes from /dev/urandom
  *                 or allocating the specified number of bytes.               
  *
  * @return char pointer pointing to address having buf_len number of bytes.
  */
unsigned char* pin_get_random_buf(int buf_len, pin_errbuf_t *rebufp);



/** return a random byte from the index of the given buffer
  *
  * The char pointer returned by this function will point to a buffer that
  * has the specified number of random bytes, these random bytes will be 
  * read from the device file /dev/urandom.
  *
  * @param  buf     char pointer pointing to address having buf_len number of 
  *                 random bytes
  *
  * @param buf_len  The length of the passed buffer, this value will be used
  *                 make sure that we do not exceed our read beyond the
  *                 length of the buffer.     
  *         
  * @param index    Integer value specifying from which index the byte should
  *                 should be read and returned from the buffer
  *
  * @param rebufp   error buffer, this will be set in case the specified index is
  *                 negative or exceeds the length of the buffer.
  *
  * @return integer random byte from the index of the given buffer
  */
int pin_get_random_byte(unsigned char *buf, int buf_len, int index, pin_errbuf_t *ebufp);

#if defined(__cplusplus)
}
#endif

#endif

