/*	
 *	@(#)$Id: bill.h /cgbubrm_commoninclude/4 2022/02/16 01:40:57 mkothari Exp $
 *	
* Copyright (c) 1996, 2022, Oracle and/or its affiliates. All rights reserved.
 *	
 *	This material is the confidential property of Oracle Corporation or its
 *	licensors and may be used, reproduced, stored or transmitted only in
 *	accordance with a valid Oracle license or sublicense agreement.
 */

#ifndef _PCM_BILL_OPS_H_
#define _PCM_BILL_OPS_H_

/*
 * This file contains the opcode definitions for the Billing PCM API.
 */

/* 
   NAME: TOTAL RANGE; USED RANGE; RESERVED RANGE; ASSOCIATED FM (if any)
   =====================================================================
   PCM_BILL_OPS:    95..149,    95..149,    -..- ;	fm_bill
		    921..950,   921..948,   950
		    1121..1130, 1121..1125, 1128..1130
		    1261..1270, 1161..1162, 1163..1170
   PCM_BILL_POL_OPS: 400..449; 400..436; 437..449;	fm_bill_pol
 */

#include "ops/base.h"

	/*
	 * Opcodes for Billing FM (95 - 149)
	 */
#define PCM_OP_BILL_SPONSOR_GROUP_SET_PARENT		95
#define PCM_OP_SUBSCRIPTION_SPONSOR_GROUP_SET_PARENT	95
#define PCM_OP_BILL_RERATE_REBILL			96
#define PCM_OP_SUBSCRIPTION_RERATE_REBILL		96
#define PCM_OP_BILL_SPONSOR_GROUP_DELETE		97	
#define PCM_OP_SUBSCRIPTION_SPONSOR_GROUP_DELETE	97	
#define PCM_OP_BILL_CURRENCY_CONVERT_AMOUNTS		98
#define PCM_OP_BILL_CURRENCY_QUERY_CONVERSION_RATES	99
#define PCM_OP_BILL_CANCEL_PRODUCT			100
#define PCM_OP_SUBSCRIPTION_CANCEL_PRODUCT	100
#define PCM_OP_BILL_CHARGE			101      /*PCM_OBSOLETE*/ /* Moved to fm_pymt */
#define PCM_OP_BILL_CYCLE_FORWARD		102
#define PCM_OP_SUBSCRIPTION_CYCLE_FORWARD	102
#define PCM_OP_BILL_CYCLE_FOLD			103
#define PCM_OP_SUBSCRIPTION_CYCLE_FOLD		103
#define PCM_OP_BILL_CYCLE_ARREARS		104
#define PCM_OP_SUBSCRIPTION_CYCLE_ARREARS	104
#define PCM_OP_BILL_DEBIT			105    /* Moved to fm_pymt */
#define PCM_OP_BILL_SET_LIMIT			106    /* Obsolete */	
#define PCM_OP_BILL_PURCHASE_PRODUCT		107
#define PCM_OP_SUBSCRIPTION_PURCHASE_PRODUCT	107
#define PCM_OP_BILL_PURCHASE_DEAL		108
#define PCM_OP_SUBSCRIPTION_PURCHASE_DEAL	108
#define PCM_OP_BILL_RFR				109	/* Obsolete */
#define PCM_OP_BILL_MAKE_BILL			110
#define PCM_OP_BILL_MAKE_INVOICE		111	/* obsolete */
#define PCM_OP_BILL_ACCOUNTING			112	/* obsolete */
#define PCM_OP_BILL_COLLECT			113     /*PCM_OBSOLETE*/ /* moved to fm_pymt */
#define PCM_OP_BILL_CHARGE_CC			114 	/*PCM_OBSOLETE*/ /* moved to fm_pymt */
#define PCM_OP_BILL_VALIDATE			115	/*PCM_OBSOLETE*/ /* moved to fm_pymt */
#define PCM_OP_BILL_CYCLE_TAX			116 
#define PCM_OP_BILL_GROUP_CREATE		117 
#define PCM_OP_BILL_GROUP_DELETE		118
#define PCM_OP_BILL_GROUP_ADD_MEMBER            119
#define PCM_OP_BILL_GROUP_DELETE_MEMBER         120
#define PCM_OP_BILL_GROUP_GET_CHILDREN		121
#define PCM_OP_BILL_GROUP_GET_PARENT		122
#define PCM_OP_BILL_ITEM_DISPUTE		123	/*PCM_OBSOLETE*/
#define PCM_OP_AR_ITEM_DISPUTE                  123
#define PCM_OP_BILL_ITEM_SETTLEMENT		124	/*PCM_OBSOLETE*/
#define PCM_OP_AR_ITEM_SETTLEMENT               124
#define PCM_OP_BILL_ITEM_ADJUSTMENT		125	/*PCM_OBSOLETE*/
#define PCM_OP_AR_ITEM_ADJUSTMENT               125
#define PCM_OP_BILL_ITEM_TRANSFER		126
#define PCM_OP_BILL_ITEM_WRITEOFF		127	/*PCM_OBSOLETE*/
#define PCM_OP_AR_ITEM_WRITEOFF			127
#define PCM_OP_BILL_ITEM_SEARCH			128	/*PCM_OBSOLETE*/  /* moved to fm_pymt */
#define PCM_OP_BILL_SELECT_ITEMS		129	/*PCM_OBSOLETE*/  /* moved to fm_pymt */
#define PCM_OP_BILL_RCV_PAYMENT			130
#define PCM_OP_BILL_FIND			131
#define PCM_OP_BILL_SET_PRODINFO		132
#define PCM_OP_SUBSCRIPTION_SET_PRODINFO	132
#define PCM_OP_BILL_LEDGER_REPORT		133	/*PCM_OBSOLETE*/
#define PCM_OP_GL_LEDGER_REPORT		        133
#define PCM_OP_BILL_CHARGE_INVOICE		134	/*PCM_OBSOLETE*/	/* obsolete */
#define PCM_OP_BILL_RECOVER			135	/*PCM_OBSOLETE*/    /* moved to fm_pymt */
#define PCM_OP_BILL_RECOVER_CC			136	/*PCM_OBSOLETE*/  /* moved to fm_pymt */
#define PCM_OP_BILL_VALIDATE_CC			137	/*PCM_OBSOLETE*/ /* moved to fm_pymt */
#define PCM_OP_BILL_REVERSE_PAYMENT		138
#define PCM_OP_BILL_REVERSE			139
#define PCM_OP_BILL_CHARGE_DDEBIT		140	/*PCM_OBSOLETE*/  /* moved to fm_pymt */
#define PCM_OP_BILL_EVENT_ADJUSTMENT		141	/*PCM_OBSOLETE*/
#define PCM_OP_AR_EVENT_ADJUSTMENT		141
#define PCM_OP_BILL_SPONSOR_GROUP_CREATE	142
#define PCM_OP_SUBSCRIPTION_SPONSOR_GROUP_CREATE	142
#define PCM_OP_BILL_SPONSOR_GROUP_ADD_MEMBER		143
#define PCM_OP_SUBSCRIPTION_SPONSOR_GROUP_ADD_MEMBER	143
#define PCM_OP_BILL_SPONSOR_GROUP_DELETE_MEMBER 	144
#define PCM_OP_SUBSCRIPTION_SPONSOR_GROUP_DELETE_MEMBER 144
#define PCM_OP_BILL_SPONSOR_GROUP_MODIFY		145
#define PCM_OP_SUBSCRIPTION_SPONSOR_GROUP_MODIFY	145
#define PCM_OP_BILL_ITEM_EVENT_SEARCH		146
#define PCM_OP_BILL_VIEW_INVOICE		147
#define PCM_OP_BILL_SET_INVOICE_STATUS		148	/* obsolete */
#define PCM_OP_BILL_GROUP_MOVE_MEMBER		149

	/* More opcodes for Billing FM */
#define PCM_OP_BILL_BILL_WRITEOFF		921	/*PCM_OBSOLETE*/ 
#define PCM_OP_AR_BILL_WRITEOFF 		921
#define PCM_OP_BILL_ACCOUNT_WRITEOFF		922	/*PCM_OBSOLETE*/ 
#define PCM_OP_AR_ACCOUNT_WRITEOFF		922
#define PCM_OP_BILL_ACCOUNT_ADJUSTMENT		923	/*PCM_OBSOLETE*/ 
#define PCM_OP_AR_ACCOUNT_ADJUSTMENT		923
#define PCM_OP_BILL_PURCHASE_FEES		924
#define PCM_OP_SUBSCRIPTION_PURCHASE_FEES	924
#define PCM_OP_BILL_ITEM_REFUND  		925
#define PCM_OP_BILL_CANCEL_DEAL			926
#define PCM_OP_SUBSCRIPTION_CANCEL_DEAL		926
#define PCM_OP_BILL_VALIDATE_DD			927	/*PCM_OBSOLETE*/   /* moved to fm_pymt */
#define PCM_OP_BILL_CHARGE_DD			928	/*PCM_OBSOLETE*/   /* moved to fm_pymt */
#define PCM_OP_BILL_RECOVER_DD			929	/*PCM_OBSOLETE*/   /* moved to fm_pymt */
#define PCM_OP_BILL_CHANGE_DEAL			930
#define PCM_OP_SUBSCRIPTION_CHANGE_DEAL		930
#define PCM_OP_BILL_TRANSFER_BALANCE		931
#define PCM_OP_SUBSCRIPTION_CHANGE_OPTIONS	932
#define PCM_OP_BILL_CHANGE_OPTIONS		932
#define PCM_OP_SUBSCRIPTION_TRANSITION_DEAL	933
#define PCM_OP_BILL_TRANSITION_DEAL		933
#define PCM_OP_SUBSCRIPTION_TRANSITION_PLAN	934
#define PCM_OP_BILL_TRANSITION_PLAN		934
#define PCM_OP_SUBSCRIPTION_VALIDATE_DEAL_DEPENDENCY	935
#define PCM_OP_BILL_VALIDATE_DEAL_DEPENDENCY	935
#define PCM_OP_BILL_SET_BILL_SUPPRESSION        936
#define PCM_OP_BILL_SET_ACCOUNT_SUPPRESSION     937
#define PCM_OP_BILL_REMOVE_ACCOUNT_SUPPRESSION  938
#define PCM_OP_BILL_GET_ARA_SUMMARY  		939
#define PCM_OP_BILL_ITEM_ASSIGN			940
#define PCM_OP_BILL_RECORD_EVENT		941
#define PCM_OP_BILL_TAX_EVENT			942
#define PCM_OP_BILL_UPDATE_JOURNAL		943
#define PCM_OP_SUBSCRIPTION_HANDLE_SYSTEM_EVENTS 944
#define PCM_OP_BILL_CREATE_SPONSORED_ITEMS      945
#define PCM_OP_BILL_EXTRACT_SPONSOREE_IMPACTS_FROM_ITEM 946
#define PCM_OP_BILL_GET_ITEM_EVENT_CHARGE_DISCOUNT 947
#define PCM_OP_BILL_SET_LIMIT_AND_CR 		948
#define PCM_OP_BILL_GET_LIMIT            949
	/* reserve 950 */

	/* opcodes for notification */
#define PCM_OP_BILL_NOTIFY_BILL_DUE 		1110
	/* reserve 1111 - 1120 */

	/* opcodes for On Demand Billing */
#define PCM_OP_BILL_MAKE_BILL_ON_DEMAND		1121 
#define PCM_OP_BILL_MAKE_BILL_NOW     		1122
	/* Opcodes for trial billing */
#define PCM_OP_BILL_MAKE_TRIAL_BILL		1123

        /* opcodes for Stop Billing */
#define PCM_OP_BILL_SUSPEND_BILLING		1124
#define PCM_OP_BILL_RESUME_BILLING		1125
#define PCM_OP_BILL_MAKE_CORRECTIVE_BILL	1126

	/* opcode for delete bill group paying members */
#define PCM_OP_BILL_GROUP_REMOVE_PAYING_MEMBERS 1127
        /* reserve 1128 - 1130 */


        /* opcodes for ledger_report */
#define PCM_OP_BILL_POST_LEDGER_REPORT          1261	/*PCM_OBSOLETE*/
#define PCM_OP_GL_POST_LEDGER_REPORT            1261
#define PCM_OP_BILL_LIST_LEDGER_REPORT          1262	/*PCM_OBSOLETE*/
#define PCM_OP_GL_LIST_LEDGER_REPORT            1262
#define PCM_OP_GL_POL_EXPORT_GL         	1263
#define PCM_OP_GL_POL_PRE_UPDATE_JOURNAL       	1264
        /* reserved - 1270 */


	/* opcodes for billing policy FM */
#define PCM_OP_BILL_POL_COLLECT			400	/*PCM_OBSOLETE*/      /* moved to fm_pymt_pol */
#define PCM_OP_BILL_POL_VALIDATE		401	/*PCM_OBSOLETE*/      /* moved to fm_pymt_pol */
#define PCM_OP_BILL_POL_SPEC_COLLECT		402	/*PCM_OBSOLETE*/      /* moved to fm_pymt_pol */
#define PCM_OP_BILL_POL_SPEC_VALIDATE		403	/*PCM_OBSOLETE*/      /* moved to fm_pymt_pol */
#define PCM_OP_BILL_POL_VALID_DISPUTE		404  
#define PCM_OP_BILL_POL_VALID_SETTLEMENT	405
#define PCM_OP_BILL_POL_VALID_ADJUSTMENT	406
#define PCM_OP_BILL_POL_VALID_TRANSFER		407
#define PCM_OP_BILL_POL_VALID_WRITEOFF		408
#define PCM_OP_BILL_POL_SPEC_BILLNO		409
#define PCM_OP_BILL_POL_UNDER_PAYMENT		410	/*PCM_OBSOLETE*/  	/* moved to fm_pymt_pol */
#define PCM_OP_BILL_POL_OVER_PAYMENT		411	/*PCM_OBSOLETE*/        /* moved to fm_pymt_pol */
#define PCM_OP_BILL_POL_FORMAT_INVOICE		412	/* obsolete */    
/*
 * RESERVE THE OPCODE NUMBER FOR BILL_GROUP_AUTHORIZATION.
 */
/* #ifdef 	BILL_GROUP_AUTHORIZATION */
#define PCM_OP_BILL_POL_SPEC_RELATION		413	/* Obsolete */
/* #endif */	/* BILL_GROUP_AUTHORIZATION */

#define PCM_OP_BILL_POL_PRE_FOLD				414
#define PCM_OP_SUBSCRIPTION_POL_PRE_FOLD			414
#define PCM_OP_BILL_POL_BILL_PRE_COMMIT				415
#define PCM_OP_BILL_POL_PRE_COLLECT				416	/*PCM_OBSOLETE*/  /* moved to fm_pymt_pol */
#define PCM_OP_BILL_POL_PURCHASE_PROD_PROVISIONING		417
#define PCM_OP_SUBSCRIPTION_POL_PURCHASE_PROD_PROVISIONING	417
#define PCM_OP_BILL_POL_CANCEL_PROD_PROVISIONING		418
#define PCM_OP_SUBSCRIPTION_POL_CANCEL_PROD_PROVISIONING	418
#define PCM_OP_BILL_POL_GET_PROD_PROVISIONING_TAGS		419
#define PCM_OP_SUBSCRIPTION_POL_GET_PROD_PROVISIONING_TAGS	419
#define PCM_OP_BILL_POL_VALID_INVOICE_STATUS			420 /*obsolete*/
#define PCM_OP_BILL_POL_SPEC_FUTURE_CYCLE			421
#define PCM_OP_BILL_POL_SPEC_CYCLE_FEE_INTERVAL			422
#define PCM_OP_SUBSCRIPTION_POL_SPEC_CYCLE_FEE_INTERVAL		422
#define PCM_OP_BILL_POL_SPEC_CANCEL				423
#define PCM_OP_SUBSCRIPTION_POL_SPEC_CANCEL			423
#define PCM_OP_BILL_POL_POST_BILLING				424
#define	PCM_OP_BILL_POL_GET_PENDING_ITEMS			425
#define PCM_OP_BILL_POL_CONFIG_EET              		426
#define PCM_OP_SUBSCRIPTION_POL_CONFIG_EET              	426
#define PCM_OP_SUBSCRIPTION_POL_PRE_TRANSITION_DEAL		427
#define PCM_OP_BILL_POL_PRE_TRANSITION_DEAL             	427
#define PCM_OP_BILL_POL_PRE_TRANSITION_PLAN			428
#define PCM_OP_SUBSCRIPTION_POL_PRE_TRANSITION_PLAN		428
#define PCM_OP_BILL_POL_PRE_SET_LIMIT_AND_CR                    429
#define PCM_OP_BILL_POL_POST_SET_LIMIT_AND_CR			430
#define PCM_OP_BILL_POL_CHECK_SUPPRESSION       		431


#define PCM_OP_BILL_POL_CALC_PYMT_DUE_T				432
#define PCM_OP_BILL_POL_EVENT_SEARCH				433 /* obsolete */
#define PCM_OP_BILL_POL_REVERSE_PAYMENT				434
#define PCM_OP_BILL_POL_CONFIG_BILLING_CYCLE			435
#define PCM_OP_BILL_POL_GET_ITEM_TAG				436
#define PCM_OP_BILL_POL_GET_EVENT_SPECIFIC_DETAILS 		437
#define PCM_OP_BILL_POL_VALID_CORRECTIVE_BILL 			438
#define PCM_OP_BILL_POL_ITEM_REFUND                             439
#define PCM_OP_BILL_POL_TOPUP_SET_VALIDITY                      440
#define PCM_OP_BILL_POL_POST_TOPUP                              441


	/* reserve 442 - 449 */

#endif /* _PCM_BILL_OPS_H_ */


