/*	
* Copyright (c) 1996, 2023, Oracle and/or its affiliates.
 *	
 *	This material is the confidential property of Oracle Corporation or its
 *	licensors and may be used, reproduced, stored or transmitted only in
 *	accordance with a valid Oracle license or sublicense agreement.
 */

#ifndef _PCM_SUBSCRIPTION_OPS_H_
#define _PCM_SUBSCRIPTION_OPS_H_

/*
 * This file contains the opcode definitions for the Billing PCM API.
 */

/* 
   NAME: TOTAL RANGE; USED RANGE; RESERVED RANGE; ASSOCIATED FM (if any)
   =====================================================================
   PCM_SUBSCRIPTION_OPS:     3751..3775,9061..9100;3751..3775,9061..9073;9074..9100; 
				fm_subscription

   PCM_SUBSCRIPTION_POL_OPS: 3776..3800; 3776..3792 ; 3793..3800; 
				fm_subscription_pol
 */

#include "ops/base.h"

	/*
	 * Opcodes for Subscription Management Standard FM (3751 - 3775) and (9061 - 9100)
	 */
#define PCM_OP_SUBSCRIPTION_PURCHASE_DISCOUNT		3751
#define PCM_OP_SUBSCRIPTION_CANCEL_DISCOUNT		3752
#define PCM_OP_SUBSCRIPTION_SET_DISCOUNTINFO		3753
#define PCM_OP_SUBSCRIPTION_SET_DISCOUNT_STATUS		3754
#define PCM_OP_SUBSCRIPTION_CYCLE_ROLLOVER     		3755
#define PCM_OP_SUBSCRIPTION_CYCLE_DISCOUNT     		3756
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_CREATE	3757
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_MODIFY	3758
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_DELETE	3759
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_SET_PARENT    3760
#define PCM_OP_SUBSCRIPTION_ORDERED_BALGRP      	3761
#define PCM_OP_SUBSCRIPTION_SET_MAPPING_TABLE      	3762
#define PCM_OP_SUBSCRIPTION_TRANSFER_SUBSCRIPTION      	3763
#define PCM_OP_SUBSCRIPTION_CANCEL_SUBSCRIPTION      	3764
#define PCM_OP_SUBSCRIPTION_RATE_CHANGE		      	3765

/*
Moved PCM_OP_SUBSCRIPTION_INSERT_RERATE_REQUEST opcode
to PCM_OP_RERATE_INSERT_RERATE_REQUEST.
Using same opcode number as before.
*/
#define PCM_OP_SUBSCRIPTION_INSERT_RERATE_REQUEST      	3766	/*PCM_OBSOLETE*/

#define PCM_OP_SUBSCRIPTION_VALIDATE_DISCOUNT_DEPENDENCY	3767
#define PCM_OP_SUBSCRIPTION_PREP_RATE_CHANGE		3768
#define PCM_OP_SUBSCRIPTION_ORDERED_BALGRP_BULK_MODIFY	3769
#define PCM_OP_SUBSCRIPTION_MONITORS_UPDATE		3770
#define PCM_OP_SUBSCRIPTION_VALIDATE_MONITOR_MEMBERS    3771
#define PCM_OP_SUBSCRIPTION_DISCOUNT_ANALYSIS		3772
#define PCM_OP_SUBSCRIPTION_COUNT_LINES			3773	/*PCM_OBSOLETE*/
#define PCM_OP_SUBSCRIPTION_COUNT_SUBSCRIPTIONS		3773
#define PCM_OP_SUBSCRIPTION_NOTIFY_AGGREGATION          3774
#define PCM_OP_SUBSCRIPTION_UPDATE_CDC			3775
#define PCM_OP_SUBSCRIPTION_UPDATE_SUBSCRIPTION_COUNT   9061
#define PCM_OP_SUBSCRIPTION_GET_PURCHASED_OFFERINGS   	9062
#define PCM_OP_SUBSCRIPTION_CALC_BEST_PRICING   	9063
#define PCM_OP_SUBSCRIPTION_CALCULATE_VALIDITY		9064
#define PCM_OP_SUBSCRIPTION_SET_VALIDITY		9065
#define PCM_OP_SUBSCRIPTION_PROVISION_ERA		9066
#define PCM_OP_SUBSCRIPTION_SET_VALIDITY_FROM_STRING	9067
#define PCM_OP_SUBSCRIPTION_APPLY_RATE			9068
#define PCM_OP_SUBSCRIPTION_TRANSFER_ROLLOVER		9069
#define PCM_OP_SUBSCRIPTION_GET_ACTG_DATES		9070
#define PCM_OP_SUBSCRIPTION_RERATE_NOTIFY_CYCLE		9071
#define PCM_OP_SUBSCRIPTION_SET_BUNDLE			9072
#define PCM_OP_SUBSCRIPTION_SERVICE_BALGRP_TRANSFER	9073
#define PCM_OP_SUBSCRIPTION_CALC_QUOTE			9074
#define PCM_OP_SUBSCRIPTION_HANDLE_PROMO_EVENT		9075
#define PCM_OP_SUBSCRIPTION_CRUD_OFFER_OVERRIDE	        9076
#define PCM_OP_SUBSCRIPTION_GET_PRICE_TAGS		9077

	/* reserve 9078- 9100 */

	/*
	 * Opcodes for Subscription Management Policy FM (3776 - 3800)
	 */
#define PCM_OP_SUBSCRIPTION_POL_SPEC_CANCEL_DISCOUNT	3776
#define PCM_OP_SUBSCRIPTION_POL_SNOWBALL_DISCOUNT	3777
#define PCM_OP_SUBSCRIPTION_POL_GET_SPONSORS     	3778
#define PCM_OP_SUBSCRIPTION_POL_SPEC_FOLD        	3779
#define PCM_OP_SUBSCRIPTION_POL_SPEC_RERATE        	3780
#define PCM_OP_SUBSCRIPTION_POL_PREP_FOLD        	3781
#define PCM_OP_SUBSCRIPTION_POL_PREP_MEMBERS        	3782
#define PCM_OP_SUBSCRIPTION_POL_COUNT_LINES		3783	/*PCM_OBSOLETE*/
#define PCM_OP_SUBSCRIPTION_POL_COUNT_SUBSCRIPTIONS	3783
#define PCM_OP_SUBSCRIPTION_POL_NOTIFY_AGGREGATION      3784
#define PCM_OP_SUBSCRIPTION_POL_UPDATE_CDC		3785
#define PCM_OP_SUBSCRIPTION_POL_UPDATE_SUBSCRIPTION_COUNT   3786
#define PCM_OP_SUBSCRIPTION_POL_GENERATE_RERATE_REQUEST   3787
#define PCM_OP_SUBSCRIPTION_POL_AUTO_SUBSCRIBE_MEMBERS   3788
#define PCM_OP_SUBSCRIPTION_POL_AUTO_SUBSCRIBE_SERVICE   3789
#define PCM_OP_SUBSCRIPTION_POL_POST_TRANSFER_SUBSCRIPTION   3790
#define PCM_OP_SUBSCRIPTION_POL_PRE_CYCLE_DISCOUNT	3791
#define PCM_OP_SUBSCRIPTION_POL_VALIDATE_OFFERING 	3792
#define PCM_OP_SUBSCRIPTION_POL_PRE_PROMO_EVENT		3793
#define PCM_OP_SUBSCRIPTION_POL_POST_PROMO_EVENT	3794
#define PCM_OP_SUBSCRIPTION_NOTIFY_PRODUCT_EXPIRY	3795
#define PCM_OP_SUBSCRIPTION_NOTIFY_SUBSCRIPTION_RENEWAL_DUE 	3796
#define PCM_OP_SUBSCRIPTION_POL_CRUD_OFFER_OVERRIDE     3797
#define PCM_OP_SUBSCRIPTION_POL_CANCEL_ON_FAILURE       3798
#define PCM_OP_SUBSCRIPTION_NOTIFY_ONETIME_PRODUCT_EXPIRY	3799

	/* 3800-3900 reserved for collection
	 * 3900-3950 reserved for cust reg
	 * 3950-3975 reserved for ums */

	/* reserving 3976-3999 for subscription */
#define PCM_OP_SUBSCRIPTION_POL_ORDERED_BALGRP_PRIORITY	3976
#define PCM_OP_SUBSCRIPTION_NOTIFY_SVC_LIFECYCLE_STATE_CHANGE	3977
#define PCM_OP_SUBSCRIPTION_NOTIFY_DEAL_EXPIRY	3978
#define PCM_OP_SUBSCRIPTION_POL_PURCHASE_PRODUCT 3979
#define PCM_OP_SUBSCRIPTION_POL_RERATE_REBILL 3980

#endif /* _PCM_SUBSCRIPTION_OPS_H_ */

