###########
#
#
# Copyright (c) 2004, 2024, Oracle and/or its affiliates.
#
#      This material is the confidential property of Oracle Corporation or its
#      licensors and may be used, reproduced, stored or transmitted only in
#      accordance with a valid Oracle license or sublicense agreement.
#
###########

OS=linux
VERSION=15.0

####

PINDIR=../../..
INCDIR=$(PINDIR)/include
LIBDIR=$(PINDIR)/lib

##########
CC_linux = gcc
CC = $(CC_$(OS))

C++_linux = gcc
C++ = $(C++_$(OS))
##########

CFLAGS_linux= -fPIC
CFLAGS= $(CFLAGS_$(OS)) -D_REENTRANT -DFOR_CM -DFM_BILL_POL_DLL -DASSIGN_NULL_AFTER_ELEM_PUT -DASSIGN_NULL_AFTER_SUBSTR_PUT -DASSIGN_NULL_AFTER_FLD_PUT

C++FLAGS_linux = -x c++ -fPIC -DPIN_NOT_USING_OSTREAM
C++FLAGS= $(C++FLAGS_$(OS)) -DPCMCPP_CONST_SAFE -DASSIGN_NULL_AFTER_ELEM_PUT -DASSIGN_NULL_AFTER_SUBSTR_PUT -DASSIGN_NULL_AFTER_FLD_PUT


CPPFLAGS = -I$(INCDIR) -DPCMCPP_CONST_SAFE -DFOR_CM -DFM_BILL_POL_DLL

LDFLAGS_linux= -shared
LDFLAGS = $(LDFLAGS_$(OS)) -L$(LIBDIR)

SL_EXT_linux= so
SL_EXT= $(SL_EXT_$(OS))

###########

INCFILES= $(INCDIR)/pin_cust.h $(INCDIR)/pcm.h \
	$(INCDIR)/pin_errs.h $(INCDIR)/pinlog.h \
	$(INCDIR)/pin_act.h $(INCDIR)/pin_bill.h \
	$(INCDIR)/pin_flds.h $(INCDIR)/pin_currency.h

#

FILES= fm_bill_pol_config.c \
	fm_bill_pol_init.c \
	fm_bill_pol_spec_billno.c \
	fm_bill_pol_valid_dispute.c \
	fm_bill_pol_valid_settlement.c \
	fm_bill_pol_valid_adjustment.c \
	fm_bill_pol_valid_transfer.c \
	fm_bill_pol_valid_writeoff.c \
	fm_bill_pol_bill_pre_commit.c \
	fm_bill_pol_spec_future_cycle.c \
	fm_bill_pol_get_pending_items.c \
	fm_bill_pol_get_event_specific_details.c \
	fm_bill_pol_post_billing.c \
	fm_bill_pol_check_suppression.c \
	fm_bill_pol_calc_pymt_due_t.c \
	fm_bill_pol_event_search.c \
	fm_bill_pol_reverse_payment.c \
	fm_bill_pol_config_billing_cycle.c

#

OBJECTS= fm_bill_pol_config.o \
	fm_bill_pol_init.o \
	fm_bill_pol_spec_billno.o \
	fm_bill_pol_valid_dispute.o \
	fm_bill_pol_valid_settlement.o \
	fm_bill_pol_valid_adjustment.o \
	fm_bill_pol_valid_transfer.o \
	fm_bill_pol_valid_writeoff.o \
	fm_bill_pol_bill_pre_commit.o \
	fm_bill_pol_spec_future_cycle.o \
	fm_bill_pol_get_pending_items.o \
	fm_bill_pol_get_event_specific_details.o \
	fm_bill_pol_post_billing.o \
	fm_bill_pol_check_suppression.o \
	fm_bill_pol_calc_pymt_due_t.o \
	fm_bill_pol_event_search.o \
	fm_bill_pol_reverse_payment.o \
	fm_bill_pol_config_billing_cycle.o

#

C++_FILES= fm_bill_pol_get_item_tag.cpp

C++_OBJECTS= fm_bill_pol_get_item_tag.o

LIBBILL=fm_bill_pol_custom.$(SL_EXT)

###########

all: $(LIBBILL)

clean:
	rm -f $(OBJECTS) $(C++_OBJECTS) core

clobber: clean
	rm -f $(LIBBILL)

lint:
	lint $(CPPFLAGS) $(FILES)

tags: FRC


###########

$(LIBBILL): $(OBJECTS) $(C++_OBJECTS) $(INCFILES) Makefile
	$(C++) -o $(LIBBILL) $(LDFLAGS) $(OBJECTS) $(C++_OBJECTS) -lm -lpsiu_for_cm

$(OBJECTS): $(INCFILES) Makefile $(FILES)
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $(FILES)

$(C++_OBJECTS): $(INCFILES) Makefile $(C++_FILES)
	$(C++) -c $(C++FLAGS) $(CPPFLAGS) $(C++_FILES)

#

FRC:

